#!/usr/bin/env bash
# This script installs nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo systemctl restart nginx
