#!/usr/bin/env bash
# This script configures nginx server to to have a 404 page

sudo apt-get update
sudo apt-get -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html > /dev/null

sudo sed -i 's/location \/ {/location \/redirect_me { return 301 https:\/\/www.youtube.com\/watch?v=XqZsoesa55w;/' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server;/a\\n\terror_page 404 /404.html;\n\t\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

sudo nginx -t
sudo systemctl restart nginx
