#!/usr/bin/env bash
# This script adds a custom header to the http response
# shellcheck disable=SC2154

sudo apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo sed -i "/listen 80 default_server;/a add_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-available/default

sudo nginx -t

sudo service nginx restart
