#!/usr/bin/env bash
# This script installs haproxy and configures it using roundrobin algorithm

sudo apt-get -y update
sudo apt-get -y install haproxy

echo -e "frontend http\n\tbind *:80\n\tdefault_backend myservers\n" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null
echo -e "backend myservers\n\tbalance roundrobin\n\tserver server 439124-web-01 54.161.250.96:80 check\n\tserver server 439124-web-02 52.91.123.172:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null

sudo service haproxy restart